apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rk-rk-poi-map-app-dev
  annotations:
    argocd/app-name: rk-rk-poi-map-app-dev
    backstage.io/kubernetes-id: rk-rk-poi-map-app-dev
    backstage.io/kubernetes-namespace: rk
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=rk-rk-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/rk-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/rk/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/rk/deployments/rk-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/rk-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://rk-poi-map-app-rk.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/raffaelklingler"
  system: workshop-system-rk
  consumesApis:
    - gateway-api-rk
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-rk
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/raffaelklingler"
